export default {
	GET_CURRENCIES: 'GET_CURRENCIES',
	GET_CURRENCIES_ERROR: 'GET_CURRENCIES_ERROR',
	GET_CONVERSION: 'GET_CONVERSION',
	GET_CONVERSION_ERROR: 'GET_CONVERSION_ERROR',
	GET_SINGLE_CONVERSION: 'GET_SINGLE_CONVERSION',
	GET_SINGLE_CONVERSION_ERROR: 'GET_SINGLE_CONVERSION_ERROR',
};
